server:
  port: 8888

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/aiimage
#    url: jdbc:mariadb://localhost:3306/aiimage
    username: root
#    password: 1234
    password: mariadb
  jpa:
    # SQL??? ?? ? ?? DBMS? ???? ??? ????
    database-platform: org.hibernate.dialect.MariaDB106Dialect
    hibernate:
      # ddl? ???? ??
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true   # SQL ??? ????? ??? ?? ??
    database: mysql  # DBMS ?? ??

logging:
  level:
    root: info
    org.hibernate.SQL: debug

jwt:
  secret: M/uO5Lteyy9MOQ/iwsThpR5yi4/R737xT4gZQlqz0xyZSTq3VAmdrcA1uCSx6JZ6cjwJDsFG+LyeX5a3wt28wQ==

root:
  path: D:/spring-prj/upload/side-menu
#  path: /Users/youngheeso/Desktop/aiimage-prj