server:
  port: 8888

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/aiimage
    username: root
    password: mariadb
  jpa:
    # SQL??? ?? ? ?? DBMS? ???? ??? ????
    database-platform: org.hibernate.dialect.MariaDB106Dialect
    hibernate:
      # ddl? ???? ??
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true   # SQL ??? ????? ??? ?? ??
    database: mysql  # DBMS ?? ??

logging:
  level:
    root: info
    org.hibernate.SQL: debug

jwt:
  secret: dJTUjZEI7FTAhIo7q9SQ2nvjaCNnuw+agmjud8tDtA6KMDqjUJY2dyQQnz/yjAA2aSZQWhELKtXjr4oiq1dKhQ==

root:
  path: /Users/bum_jun2/Desktop/LONI/Test


